name = "heyun-zjmf-worker-monitor"
main = "src/index.js"
compatibility_date = "2026-05-10"

[secrets]
required = ["ADMIN_TOKEN"]

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "zjmf-monitor"
database_id = "ca9b4623-e8f4-4610-b416-59d9e3e71b1d"
