import assert from 'node:assert/strict';
import test from 'node:test';

import { renderAdminPage } from '../src/admin-page.js';

test('管理后台页面使用 ZJMF_ADMIN_TOKEN 登录且不嵌入真实密码', () => {
  const html = renderAdminPage({ showIntro: true });

  assert.match(html, /管理面板/);
  assert.match(html, /ZJMF_ADMIN_TOKEN/);
  assert.match(html, /开始初始化监控系统/);
  assert.match(html, /id="setupIntro" class="modal"/);
  assert.match(html, /id="setupEmpty"/);
  assert.match(html, /取消/);
  assert.match(html, /确定进入/);
  assert.match(html, /进入初始化/);
  assert.match(html, /四步初始化向导/);
  assert.match(html, /首次打开网站/);
  assert.match(html, /id="setupWizardModal"/);
  assert.match(html, /id="setupMsg"/);
  assert.match(html, /id="setupStep"/);
  assert.match(html, /下一步/);
  assert.match(html, /上一步/);
  assert.match(html, /class="toplinks"[\s\S]*分析[\s\S]*状态页[\s\S]*重走初始教程[\s\S]*退出登录/);
  assert.match(html, /data-action="restart-tutorial"/);
  assert.match(html, /\/api\/admin\/setup\/reset/);
  assert.match(html, /自动获取产品列表/);
  assert.match(html, /导入选中服务器/);
  assert.match(html, /已导入服务器/);
  assert.match(html, /可换账号重复导入/);
  assert.match(html, /魔方财务登录邮箱或手机号/);
  assert.match(html, /魔方财务产品 ID/);
  assert.match(html, /当前选中服务器/);
  assert.match(html, /id="selectedHostPanel"/);
  assert.match(html, /#selectedHostPanel\{padding:12px 14px\}/);
  assert.match(html, /#selectedHostPanel \.grid2\{grid-template-columns:repeat\(4,minmax\(0,1fr\)\);gap:10px\}/);
  assert.match(html, /id="selectedHostIp"/);
  assert.match(html, /接口未返回 IP/);
  assert.doesNotMatch(html, /id="serverIdInput"/);
  assert.doesNotMatch(html, /id="serverNameInput"/);
  assert.match(html, /修改管理密码/);
  assert.match(html, /setup_completed/);
  assert.match(html, /\/api\/admin\/zjmf\/hosts/);
  assert.match(html, /\/api\/admin\/setup/);
  assert.match(html, /\/api\/admin\/password/);
  assert.match(html, /\/api\/admin\/overview/);
  assert.match(html, /\/api\/admin\/events/);
  assert.match(html, /\/api\/admin\/servers\//);
  assert.match(html, /method:'DELETE'/);
  assert.match(html, /确认删除监控项/);
  assert.match(html, /监控项/);
  assert.match(html, /事件日志/);
  assert.match(html, /新建监控项/);
  assert.match(html, /通知渠道/);
  assert.match(html, /系统更新/);
  assert.match(html, /数据保留/);
  assert.match(html, /站点品牌/);
  assert.match(html, /用于控制状态页标题与描述/);
  assert.match(html, /class="settingsStack"/);
  assert.match(html, /class="settingsCard settingsBrand"/);
  assert.match(html, /name="site_title"/);
  assert.match(html, /name="site_description"/);
  assert.match(html, /name="timezone"/);
  assert.match(html, /D1 中原始探测结果的保留天数/);
  assert.match(html, /name="data_retention_days"/);
  assert.match(html, /状态切换默认值/);
  assert.match(html, /name="suspect_threshold"/);
  assert.match(html, /name="recover_success_threshold"/);
  assert.match(html, /后台默认值/);
  assert.match(html, /后台分析页面默认时间范围/);
  assert.match(html, /name="admin_overview_range"/);
  assert.match(html, /name="admin_monitor_range"/);
  assert.match(html, /id="systemSettingsForm"/);
  assert.match(html, /data-tab="update"/);
  assert.match(html, /检查更新/);
  assert.match(html, /确定更新/);
  assert.match(html, /updateInfo/);
  assert.match(html, /\/api\/admin\/update\/check/);
  assert.match(html, /\/api\/admin\/update\/dispatch/);
  assert.match(html, /GitHub Actions/);
  assert.match(html, /GitHub 返回/);
  assert.match(html, /github_message/);
  assert.match(html, /allowError/);
  assert.match(html, /api\('\/api\/admin\/update\/check',\{allowError:true\}\)/);
  assert.match(html, /新建通知渠道/);
  assert.match(html, /编辑通知渠道/);
  assert.match(html, /id="notifyRows"/);
  assert.match(html, /id="notifyModal"/);
  assert.match(html, /name="webhook_name"/);
  assert.doesNotMatch(html, /<input value="pushplus" disabled>/);
  assert.match(html, /在状态页显示/);
  assert.match(html, /魔方财务 API/);
  assert.match(html, /HTTP\(S\)/);
  assert.match(html, /填一个能访问的域名\+端口\/网页地址/);
  assert.match(html, /TCP 端口/);
  assert.match(html, /HTTP 方法/);
  assert.match(html, /期望状态码/);
  assert.match(html, /name="http_method"/);
  assert.match(html, /name="http_expected_status"/);
  assert.match(html, /如果接口返回 IP，会自动带出 TCP 主机/);
  assert.match(html, /HTTP\(S\) \+ TCP \+ API/);
  assert.doesNotMatch(html, /三步检测：HTTP\(S\) \+ TCP \+ API/);
  assert.match(html, /连续失败 3 次/);
  assert.match(html, /webhook_headers/);
  assert.match(html, /webhook_template/);
  assert.match(html, /name="check_interval"/);
  assert.match(html, /name="api_timeout_ms"/);
  assert.match(html, /24 小时重启上限/);
  assert.doesNotMatch(html, /每小时重启上限|每日重启上限/);
  assert.match(html, /api_timeout:Math\.max/);
  assert.match(html, /data_retention_days:Number/);
  assert.match(html, /site_title:b\.site_title/);
  assert.match(html, /timezone:b\.timezone/);
  assert.match(html, /suspect_threshold:Number/);
  assert.match(html, /admin_overview_range:b\.admin_overview_range/);
  assert.match(html, /function autoFillHttpUrl/);
  assert.match(html, /autoFillHttpUrl\(form\)/);
  assert.match(html, /autoFillHttpUrl\(\$\('serverForm'\)\)/);
  assert.match(html, /name="api_password" type="text"/);
  assert.match(html, /id="editModal"/);
  assert.match(html, /#editModal \.setup-modal/);
  assert.match(html, /max-height:calc\(100vh - 48px\)/);
  assert.match(html, /overflow-y:auto/);
  assert.match(html, /#serverForm \.checkCard/);
  assert.match(html, /padding:12px 14px/);
  assert.match(html, /保存服务商/);
  assert.match(html, /保存服务器/);
  assert.match(html, /id="toast"/);
  assert.match(html, /操作中/);
  assert.match(html, /async function task/);
  assert.match(html, /showSetupMsg/);
  assert.match(html, /wasDisabled/);
  assert.match(html, /const scrub=/);
  assert.match(html, /background-size:50px 50px/);
  assert.match(html, /--bg:#f5f7fb/);
  assert.match(html, /管理后台登录后会显示/);
  assert.doesNotMatch(html, /1 密码.*2 魔方财务.*3 监控参数.*4 通知渠道/);
  assert.match(html, /old_password/);
  assert.match(html, /localStorage\.getItem\('zjmf_admin_token'\)/);
  assert.doesNotMatch(html, /if\(token\)enter\(\)\.catch/);
  assert.match(html, /startSetupBtn/);
  assert.match(html, /cancelSetupBtn/);
  assert.match(html, /async function skipSetupAndEnter/);
  assert.match(html, /\$\('cancelSetupBtn'\)\.onclick=skipSetupAndEnter/);
  assert.doesNotMatch(html, /\$\('cancelSetupBtn'\)\.onclick=showEmpty/);
  assert.match(html, /resumeSetupBtn/);
  assert.match(html, /syncSelectedHost/);
  assert.match(html, /selectedHostIp/);
  assert.match(html, /接口未返回 IP/);
  assert.doesNotMatch(html, /服务器 IP|1\.2\.3\.4/);
  assert.doesNotMatch(html, /https:\/\/example\.com\/health/);
  assert.doesNotMatch(html, /super-secret-admin-password/);
  assert.doesNotMatch(html, /删除功能暂未开放/);
  assert.doesNotMatch(html, /定时重启|scheduled_reboot/);
  assert.doesNotMatch(html, /维护策略|maintenanceView|data-tab="maintenance"/);
  assert.match(html, /<option value="service_then_power" selected>/);
  assert.match(html, /通知开关/);
  assert.match(html, /失败阶段静默/);
  assert.match(html, /name="notify_failure_silence"/);
  assert.match(html, /不勾选时，检测异常\/确认宕机会通知/);
  assert.match(html, /notify_failure_silence:false/);
  assert.match(html, /notify_failure_silence:b\.notify_failure_silence==='on'/);
  assert.doesNotMatch(html, /name="notify_failure_threshold"/);
  assert.match(html, /卡片式通知设置/);
  assert.match(html, /<option value="bark">Bark/);
  assert.match(html, /<option value="telegram">Telegram/);
  assert.match(html, /<option value="feishu">飞书机器人/);
  assert.match(html, /<option value="wecom">企业微信机器人/);
  assert.match(html, /<option value="dingtalk">钉钉机器人/);
  assert.match(html, /<option value="slack">Slack Webhook/);
  assert.match(html, /<option value="discord">Discord Webhook/);
  assert.match(html, /name="notify_token"/);
  assert.match(html, /name="notify_target"/);
  assert.match(html, /function syncNotifyFields/);
  assert.doesNotMatch(html, /showUrl=type==='pushplus'/);
});
