import assert from 'node:assert/strict';
import test from 'node:test';

import { renderAdminPage } from '../src/admin-page.js';

test('管理后台页面使用 ZJMF_ADMIN_TOKEN 登录且不嵌入真实密码', () => {
  const html = renderAdminPage();

  assert.match(html, /管理面板/);
  assert.match(html, /ZJMF_ADMIN_TOKEN/);
  assert.match(html, /\/api\/admin\/overview/);
  assert.match(html, /\/api\/admin\/events/);
  assert.match(html, /\/api\/admin\/servers\//);
  assert.match(html, /method:'DELETE'/);
  assert.match(html, /确认删除监控项/);
  assert.match(html, /监控项/);
  assert.match(html, /事件日志/);
  assert.match(html, /新建监控项/);
  assert.match(html, /通知渠道/);
  assert.match(html, /新建通知渠道/);
  assert.match(html, /编辑通知渠道/);
  assert.match(html, /id="notifyRows"/);
  assert.match(html, /id="notifyModal"/);
  assert.match(html, /name="webhook_name"/);
  assert.doesNotMatch(html, /<input value="pushplus" disabled>/);
  assert.match(html, /在状态页显示/);
  assert.match(html, /魔方财务 API/);
  assert.match(html, /webhook_headers/);
  assert.match(html, /webhook_template/);
  assert.match(html, /name="check_interval"/);
  assert.match(html, /name="api_timeout_ms"/);
  assert.match(html, /每小时重启上限/);
  assert.doesNotMatch(html, /每日重启上限/);
  assert.match(html, /api_timeout:Math\.max/);
  assert.match(html, /name="api_password" type="text"/);
  assert.match(html, /id="editModal"/);
  assert.match(html, /保存服务商/);
  assert.match(html, /保存服务器/);
  assert.match(html, /id="toast"/);
  assert.match(html, /操作中/);
  assert.match(html, /async function task/);
  assert.match(html, /wasDisabled/);
  assert.match(html, /const scrub=/);
  assert.match(html, /background-size:50px 50px/);
  assert.match(html, /--bg:#f5f7fb/);
  assert.match(html, /管理后台登录后会显示/);
  assert.match(html, /localStorage\.getItem\('zjmf_admin_token'\)/);
  assert.doesNotMatch(html, /服务器 IP|1\.2\.3\.4/);
  assert.doesNotMatch(html, /super-secret-admin-password/);
  assert.doesNotMatch(html, /删除功能暂未开放/);
  assert.doesNotMatch(html, /定时重启|scheduled_reboot/);
  assert.doesNotMatch(html, /维护策略|maintenanceView|data-tab="maintenance"/);
});
